### ISSUE TITLE
install.packages("IsoMemo")

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/drat#10]
# Download **IsomemoData** package in R

There are two methods to download this package. Run these codes in your local R console:
1) Using official CRAN repo commands (in development): 
- `install.packages("IsomemoData")`

2) Download the development version (recommended):
- `options(repos = c(getOption("repos"), PANDORA = "https://Pandora-IsoMemo.github.io/drat/"))`
- `install.packages("IsomemoData")`

## How to use the package:
- `library(IsoMemo)`
- `getData(db="IntChron")`

Proceed to run commands from this package.

# HOW TO REPORT BUGS:

If you have issues installing the packages, please report your issue here with the package name and what steps you have already done, preferably as descriptive as possible (screenshots, etc.). We will get back to you as soon as we can to solve the issue.

## Can please provide:

> - All commands that led to the installation error: 
> - The full output of `sessionInfo()`
> - The output of `options("repos")`

**Comment by jroachell15** [comment]
@isomemo Hi Ricardo, 

Is your installation successful? could you please report your issues concerning the CRAN package IsomemoData here?

**Comment by arunge** [comment]
This issue is deprecated.

Updated instructions can be found here: https://github.com/Pandora-IsoMemo/isomemo-data/blob/main/README.md
