### ISSUE TITLE
install.packages("MpiIsoData")

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/drat#12]
# Download **MpiIsoData** data API package in R
Run these codes in your local R console:

- `options(repos = c(getOption("repos"), PANDORA = "https://Pandora-IsoMemo.github.io/drat/"))`
- `install.packages("MpiIsoData")`

## How to start the app:
- `library(MpiIsoData)`

# HOW TO REPORT BUGS:

If you have issues installing the packages, please report your issue here with the package name and what steps you have already done, preferably as descriptive as possible (screenshots, etc.). We will get back to you as soon as we can to solve the issue.

## Can please provide:

> - All commands that led to the installation error: 
> - The full output of `sessionInfo()`
> - The output of `options("repos")`

**Comment by arunge** [comment]
This is deprecated. I close here.
