### ISSUE TITLE
Error installing BMSC webapp

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/drat#13]
> options(repos = c(getOption("repos"), PANDORA = "https://Pandora-IsoMemo.github.io/drat/"))
> install.packages("BMSCApp")
Installing package into ‘C:/Users/ldv15/OneDrive/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
also installing the dependency ‘BMSC’

Warning: unable to access index for repository https://Pandora-IsoMemo.github.io/drat/bin/windows/contrib/4.1:
  cannot open URL 'https://Pandora-IsoMemo.github.io/drat/bin/windows/contrib/4.1/PACKAGES'
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘BMSC’
  These will not be installed
installing the source package ‘BMSCApp’

trying URL 'https://Pandora-IsoMemo.github.io/drat/src/contrib/BMSCApp_22.02.1.tar.gz'
Content type 'application/gzip' length 15065 bytes (14 KB)
downloaded 14 KB

ERROR: dependency 'BMSC' is not available for package 'BMSCApp'
* removing 'C:/Users/ldv15/OneDrive/Documents/R/win-library/4.1/BMSCApp'

The downloaded source packages are in
        ‘C:\Users\ldv15\AppData\Local\Temp\RtmpsP6fOi\downloaded_packages’
Warning message:
In install.packages("BMSCApp") :
  installation of package ‘BMSCApp’ had non-zero exit status

**Comment by jroachell15** [comment]
@wahani Ricardo probably need to install BMSC package first then the BMSCapp right?

**Comment by jroachell15** [comment]
@isomemo 

I have Linux machine and the download worked for me, but it appears that this is a complex package that Windows machine cannot download this package fully. 

After talking to Sebastian, we propose this solution: 
1) make this public BMSCapp package and publish to CRAN. and just "install.packages("BMSCapp") ~ 15-20 timebank hours
2) Docker way: it's much easier for Documentation: download docker then run the app. ~ 5-7 timebank hours

@isomemo  which way would you like to proceed?

**Comment by arunge** [comment]
I tried to install BMSCApp on my private windows machine. I received the same error that BMSC is not available.
When trying to install BMSC I receive:

![image](https://user-images.githubusercontent.com/16759098/170071154-155fe76b-74b6-4b07-9903-ae6ed6ff0a4e.png)

So, this also speaks for the docker option.

**Comment by jroachell15** [comment]
@isomemo 
I am making the docker documentation to solve this issue now. thanks!

We will post a video on how to follow the instructions. 

with these installation commands. Its very easy. 

`docker pull ghcr.io/pandora-isomemo/bmsc-app:main`

`docker run -p 3838:3838 ghcr.io/pandora-isomemo/bmsc-app:main`

`docker run -p 3838:3838 --rm ghcr.io/pandora-isomemo/bmsc-app:main`

**Comment by isomemo** [comment]
The install is quite complicated! Most users will not even know what is a windows command line. Please try to find a simpler/automatic way of doing this.
