### ISSUE TITLE
Installation bug for MpiIsoApp

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/drat#14]
Got this error while trying to install MpiIsoApp:

An error has occurred!

lexical error: invalid char in json text. dbsources? (right here) ------^ 

Please prioritize fixing this!

**Comment by jroachell15** [comment]
@isomemo I could not reproduce this bug, 

please follow the formula for bug reporting as we established:
Can please provide:
- All commands that led to the installation error:
- The full output of sessionInfo()
- The output of options("repos")
