### ISSUE TITLE
Issue in installing Bpred in Windows

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/drat#16]
@arunge @jroachell15 

Following the installation of Bpred on Windows I get the error that a package is missing (although installation is successful). However, when executing the command library R informs that there is no package called mpiBpred. See below!

> options(repos = c(getOption("repos"), PANDORA = "https://Pandora-IsoMemo.github.io/drat/"))
> install.packages("mpiBpred")
Installing package into ‘C:/Users/fernandes/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
Warning: dependency ‘rsync’ is not available
also installing the dependencies ‘purrr’, ‘jquerylib’, ‘fs’, ‘rappdirs’, ‘generics’, ‘tidyselect’, ‘base64enc’, ‘fastmap’, ‘httpuv’, ‘mime’, ‘xtable’, ‘fontawesome’, ‘sourcetools’, ‘later’, ‘promises’, ‘commonmark’, ‘bslib’, ‘cachem’, ‘sass’, ‘rJava’, ‘xlsxjars’, ‘coda’, ‘dplyr’, ‘htmltools’, ‘jsonlite’, ‘modules’, ‘shiny’, ‘shinyMatrix’, ‘shinyWidgets’, ‘shinycssloaders’, ‘shinyjs’, ‘shinythemes’, ‘xlsx’, ‘zip’

Warning: unable to access index for repository https://Pandora-IsoMemo.github.io/drat/bin/windows/contrib/4.1:
  cannot open URL 'https://Pandora-IsoMemo.github.io/drat/bin/windows/contrib/4.1/PACKAGES'
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘mpiBpred’
  These will not be installed
trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/purrr_0.3.4.zip'
Content type 'application/zip' length 428319 bytes (418 KB)
downloaded 418 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/jquerylib_0.1.4.zip'
Content type 'application/zip' length 525866 bytes (513 KB)
downloaded 513 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/fs_1.5.2.zip'
Content type 'application/zip' length 607789 bytes (593 KB)
downloaded 593 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/rappdirs_0.3.3.zip'
Content type 'application/zip' length 58844 bytes (57 KB)
downloaded 57 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/generics_0.1.2.zip'
Content type 'application/zip' length 79160 bytes (77 KB)
downloaded 77 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/tidyselect_1.1.2.zip'
Content type 'application/zip' length 206462 bytes (201 KB)
downloaded 201 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/base64enc_0.1-3.zip'
Content type 'application/zip' length 43156 bytes (42 KB)
downloaded 42 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/fastmap_1.1.0.zip'
Content type 'application/zip' length 215473 bytes (210 KB)
downloaded 210 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/httpuv_1.6.5.zip'
Content type 'application/zip' length 1695807 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/mime_0.12.zip'
Content type 'application/zip' length 48094 bytes (46 KB)
downloaded 46 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/xtable_1.8-4.zip'
Content type 'application/zip' length 706783 bytes (690 KB)
downloaded 690 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/fontawesome_0.2.2.zip'
Content type 'application/zip' length 1529090 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/sourcetools_0.1.7.zip'
Content type 'application/zip' length 691426 bytes (675 KB)
downloaded 675 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/later_1.3.0.zip'
Content type 'application/zip' length 860098 bytes (839 KB)
downloaded 839 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/promises_1.2.0.1.zip'
Content type 'application/zip' length 2320030 bytes (2.2 MB)
downloaded 2.2 MB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/commonmark_1.8.0.zip'
Content type 'application/zip' length 270377 bytes (264 KB)
downloaded 264 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/bslib_0.3.1.zip'
Content type 'application/zip' length 5038343 bytes (4.8 MB)
downloaded 4.8 MB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/cachem_1.0.6.zip'
Content type 'application/zip' length 78968 bytes (77 KB)
downloaded 77 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/sass_0.4.1.zip'
Content type 'application/zip' length 3639643 bytes (3.5 MB)
downloaded 3.5 MB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/rJava_1.0-6.zip'
Content type 'application/zip' length 1513770 bytes (1.4 MB)
downloaded 1.4 MB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/xlsxjars_0.6.1.zip'
Content type 'application/zip' length 9485688 bytes (9.0 MB)
downloaded 9.0 MB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/coda_0.19-4.zip'
Content type 'application/zip' length 323151 bytes (315 KB)
downloaded 315 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/dplyr_1.0.9.zip'
Content type 'application/zip' length 1391908 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/htmltools_0.5.2.zip'
Content type 'application/zip' length 347373 bytes (339 KB)
downloaded 339 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/jsonlite_1.8.0.zip'
Content type 'application/zip' length 1155963 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/modules_0.10.0.zip'
Content type 'application/zip' length 110129 bytes (107 KB)
downloaded 107 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/shiny_1.7.1.zip'
Content type 'application/zip' length 4231722 bytes (4.0 MB)
downloaded 4.0 MB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/shinyMatrix_0.6.0.zip'
Content type 'application/zip' length 149923 bytes (146 KB)
downloaded 146 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/shinyWidgets_0.7.0.zip'
Content type 'application/zip' length 1422231 bytes (1.4 MB)
downloaded 1.4 MB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/shinycssloaders_1.0.0.zip'
Content type 'application/zip' length 140778 bytes (137 KB)
downloaded 137 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/shinyjs_2.1.0.zip'
Content type 'application/zip' length 1107664 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/shinythemes_1.2.0.zip'
Content type 'application/zip' length 990663 bytes (967 KB)
downloaded 967 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/xlsx_0.6.5.zip'
Content type 'application/zip' length 375174 bytes (366 KB)
downloaded 366 KB

trying URL 'https://mirror.dogado.de/cran/bin/windows/contrib/4.1/zip_2.2.0.zip'
Content type 'application/zip' length 1122174 bytes (1.1 MB)
downloaded 1.1 MB

package ‘purrr’ successfully unpacked and MD5 sums checked
package ‘jquerylib’ successfully unpacked and MD5 sums checked
package ‘fs’ successfully unpacked and MD5 sums checked
package ‘rappdirs’ successfully unpacked and MD5 sums checked
package ‘generics’ successfully unpacked and MD5 sums checked
package ‘tidyselect’ successfully unpacked and MD5 sums checked
package ‘base64enc’ successfully unpacked and MD5 sums checked
package ‘fastmap’ successfully unpacked and MD5 sums checked
package ‘httpuv’ successfully unpacked and MD5 sums checked
package ‘mime’ successfully unpacked and MD5 sums checked
package ‘xtable’ successfully unpacked and MD5 sums checked
package ‘fontawesome’ successfully unpacked and MD5 sums checked
package ‘sourcetools’ successfully unpacked and MD5 sums checked
package ‘later’ successfully unpacked and MD5 sums checked
package ‘promises’ successfully unpacked and MD5 sums checked
package ‘commonmark’ successfully unpacked and MD5 sums checked
package ‘bslib’ successfully unpacked and MD5 sums checked
package ‘cachem’ successfully unpacked and MD5 sums checked
package ‘sass’ successfully unpacked and MD5 sums checked
package ‘rJava’ successfully unpacked and MD5 sums checked
package ‘xlsxjars’ successfully unpacked and MD5 sums checked
package ‘coda’ successfully unpacked and MD5 sums checked
package ‘dplyr’ successfully unpacked and MD5 sums checked
package ‘htmltools’ successfully unpacked and MD5 sums checked
package ‘jsonlite’ successfully unpacked and MD5 sums checked
package ‘modules’ successfully unpacked and MD5 sums checked
package ‘shiny’ successfully unpacked and MD5 sums checked
package ‘shinyMatrix’ successfully unpacked and MD5 sums checked
package ‘shinyWidgets’ successfully unpacked and MD5 sums checked
package ‘shinycssloaders’ successfully unpacked and MD5 sums checked
package ‘shinyjs’ successfully unpacked and MD5 sums checked
package ‘shinythemes’ successfully unpacked and MD5 sums checked
package ‘xlsx’ successfully unpacked and MD5 sums checked
package ‘zip’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\fernandes\AppData\Local\Temp\Rtmp2LI9q0\downloaded_packages
> library(mpiBpred)
Error in library(mpiBpred) : there is no package called ‘mpiBpred’
> library("mpiBpred")
Error in library("mpiBpred") : there is no package called ‘mpiBpred’

**Comment by jroachell15** [comment]
@isomemo currently on hold, until @wahani comes back from vacation.

**Comment by isomemo** [comment]
@jroachell15 @wahani as we discussed last week this work should be on hold until I instruct otherwise. Docker did not work on some Windows computers and our IT is looking into other installer options.

**Comment by isomemo** [comment]
@wahani there is one thing that should be worked on. The documentation for the R install that describes how to address installation issues such as those above. Not only for Bpred but also for the other apps. Irrespective of the installer solution, are still going to be given the option to install apps via R.

**Comment by arunge** [comment]
Installation instruction were added to the [wiki of Bpred](https://github.com/Pandora-IsoMemo/bpred/wiki).

**Comment by isomemo** [comment]
@arunge thanks! Please ensure that this is available for all apps!
