### ISSUE TITLE
Issue Installing OsteoBioR

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/drat#18]
Via e-mail:

> I was trying to install the offline R version of OsteoBioR on my laptop ... . However, by following instructions that are published online in github, this was not working.

@CarloCocozza As written per e-mail, please let me know some more details:

- operation system you used
- R version
- Did you try the docker installation also? (Instructions are currently given for e.g. the [iso-app](https://github.com/Pandora-IsoMemo/iso-app/wiki/Getting-Started#alternative-run-application-in-a-docker-container). You can follow the instructions analogously, after [installing docker](https://github.com/Pandora-IsoMemo/iso-app/wiki/Getting-Started#install-docker), only replace the package name in the commands, that is:
  - `docker pull ghcr.io/pandora-isomemo/osteo-bior:main`
  and
  - `docker run -p 3838:3838 ghcr.io/pandora-isomemo/osteo-bior:main`, and now you can access the app **locally** via your web browser at http://0.0.0.0:3838

  Did you try this? If not, could you do so please? OsteoBioR needs compilation of C/C++/Fortran, this can cause issues on different operating systems. The best would be to use docker here. Than, we have a controlled container that has all required dependencies.

In general, in case of installation issues, best would be always to [provide](https://github.com/Pandora-IsoMemo/drat/issues/11#issue-1177898295):
> - All commands that led to the installation error:
> - The full output of sessionInfo()
> - The output of options("repos")

Note: @jan-abel-inwt is currently working on filling the wikis of all apps with respective installation instructions (for docker and the R packages). However, this is not finished yet. Thank you for your patience!

**Comment by CarloCocozza** [comment]
@arunge

I copy paste here my email:

> "Dear Antonia,
> 
> thanks for your email!
> 
> -I use Windows 64bit.
> -R versioin 4.2.2
> - The message I receive is (translated): "Warning: you cannot access the index for the repository https://Pandora-IsoMemo.github.io/drat/bin/windows/contrib/4.2:
>   it is not possible to open URL 'https://Pandora-IsoMemo.github.io/drat/bin/windows/contrib/4.2/PACKAGES'
> The package is available only in source form and requires
>   compilation of C/C++/Fortran code: 'OsteoBioR'
>   These will not be installed"
> 
> I had the same issue with MpiIsoApp. Whereas it worked properly with ReSources.
> 
> 
> All the best,"

I just downloaded Docker, but I receive this message in the home page on my desktop app: "Docker Desktop failed to start..."
What should I do?

**Comment by arunge** [comment]
@CarloCocozza Did the [installation of docker on windows](https://docs.docker.com/desktop/install/windows-install/) succeed?

**Comment by CarloCocozza** [comment]
@arunge I think it says I need to install a Linux Kernel, but I don't understand why. Probably I did need to tick on WSL 2  during the installation.

I will be out of office for a couple of hours. I can try this again at lunch time.

**Comment by arunge** [comment]
@CarloCocozza Yes, our IT said that you need to install the Linux Kernel in order to make docker run. Yes, please try to "tick on WSL 2".
More details on this can be found in https://learn.microsoft.com/en-us/windows/wsl/install#install-wsl-command. (Below there is a guide on how to change the default Linux distribution, this is **not** necessary in our case, the default is fine.)

Please let me know, which steps you did and if it succeeded! Thanks!

**Comment by CarloCocozza** [comment]
@arunge I installed the Linux Kernel but some error occurred and now the Docker says Docker Desktop Stopped...

**Comment by arunge** [comment]
@CarloCocozza, did you already try to restart the PC? That could already help to fix the issue since the installation of WSL might require docker to restart also. It may also help to rerun the docker installation and to restart again.

If that doesn't help, we could check @isomemo how we could provide support here. We do have internal IT support, but our capacity is limited and it might be worth thinking of a solution together with MPI IT service desk. E.g. we could present the installation procedure for what is needed to get the apps to work with your service desk so that they are familiar with the use case. Then, they provide on-site support in such cases. What do you think?

**Comment by CarloCocozza** [comment]
@arunge Ok, by restarting my laptop Docker works. But I don't understand where can I write the command.

**Comment by arunge** [comment]
Commands like `docker pull ghcr.io/pandora-isomemo/iso-app:main` can be put into the windows PowerShell.

**Comment by CarloCocozza** [comment]
@arunge I received the following error when copying `docker pull ghcr.io/pandora-isomemo/osteo-bior:main` into the windows powershell :

"error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=ghcr.io%2Fpandora-isomemo%2Fosteo-bior&tag=main": open //./pipe/docker_engine: The system cannot find the file specified.
PS C:\Users\Carlo>"

**Comment by CarloCocozza** [comment]
Sorry! I had to have the docker started first.

**Comment by CarloCocozza** [comment]
@arunge I followed the steps you wrote above, but the http://0.0.0.0:3838/ page is not opening. It says that the webpage might be temporary not available or permanently moved to a new address.

**Comment by isomemo** [comment]
@CarloCocozza 

See if this address works:

http://127.0.0.1:3838/

**Comment by CarloCocozza** [comment]
@arunge Yes it works!
So now, when I want to use it offline, I just need to input this address in the google bar? even without wifi connection?

**Comment by arunge** [comment]
@CarloCocozza Almostly. Of course, after e.g. restarting the computer you always must execute first:
`docker run -p 3838:3838 ghcr.io/pandora-isomemo/osteo-bior:main`, then you can put http://127.0.0.1:3838/ into your browser.

To set up an app with:
`docker pull ghcr.io/pandora-isomemo/osteo-bior:main`
 you will always need an internet connection.

But to start the app with:
`docker run -p 3838:3838 ghcr.io/pandora-isomemo/osteo-bior:main`
you do not net an internet connection.

**Comment by CarloCocozza** [comment]
@arunge I see, thanks!

I also installed iso-app, but when I click on http://127.0.0.1:3838/ I still get to OsteoBioR. Does Iso-app have a different address?

**Comment by arunge** [comment]
You always need to run the respective `docker run` command before starting another app:

```
docker run -p 3838:3838 http://ghcr.io/pandora-isomemo/<NAME_OF_REPOSITORY>:main
```

Please use the correct repository name for `<NAME_OF_REPOSITORY>`, e.g. "osteo-bior" or "iso-app"

**Comment by arunge** [comment]
In a similar way you can also install all the other apps locally. You only need to use the correct name of the app's github repository:

- to install (with internet connection): `docker pull http://ghcr.io/pandora-isomemo/<NAME_OF_REPOSITORY>:main`

- to run locally: `docker run -p 3838:3838 http://ghcr.io/pandora-isomemo/<NAME_OF_REPOSITORY>:main`

We are updating the respective wikis currently.

@CarloCocozza Is there any open question here, or can I close this issue?

**Comment by CarloCocozza** [comment]
@arunge I used this command: `docker run -p 3838:3838 ghcr.io/pandora-isomemo/iso-app:main`

 and I received this error:
docker: Error response from daemon: driver failed programming external connectivity on endpoint focused_thompson (95be962aef7fc60921228cc8f875cd1753f6d1058d13bbb98089033be2a7ec28): Bind for 0.0.0.0:3838 failed: port is already allocated.

**Comment by arunge** [comment]
Than there is an app still running and the port is blocked. You must halt the execution of docker in the PowerShell. In Linux one can do this with Ctrl+C or by closing the terminal.

**Comment by CarloCocozza** [comment]
@arunge I tried both by closing docker, shell and browser, or by Ctrl+C. In both cases I receive still the same error and the address only takes me to OsteoBioR

**Comment by arunge** [comment]
@isomemo Do you know how to switch between apps using the windows powerShell or the windows shell (cmd.exe)? I am using the terminal in linux and there is no such issue, I only need `Ctrl+C` to stop running the previous app.

**Comment by arunge** [comment]
@CarloCocozza @isomemo In case the above error occurs
> docker: Error response from daemon: driver failed ... Bind for 0.0.0.0:3838 failed: port is already allocated.

one must **stop the container that is still running**. This can be done as follows:

1. *Check* which container is running with: `docker ps`
  ![image](https://user-images.githubusercontent.com/16759098/210572033-30e9d416-5d7d-4311-9a43-c829812880dc.png)
3. *Stop* the container using exactly the id from above (here `ab2a252f9269`): `docker stop <YOUR_ID>`
4. *Remove* the container using exactly the id from above: `docker rm <YOUR_ID>`
  ![image](https://user-images.githubusercontent.com/16759098/210574291-c57afb39-10d2-449a-a130-9c97c05561d6.png)
6. *Check* if no container is running anymore: `docker ps`
  The table should be empty now:
  ![image](https://user-images.githubusercontent.com/16759098/210574620-5b243071-57ad-4561-ad74-883731cc4f8f.png)


Now, one can start a new container, e.g. with
`docker run -p 3838:3838 ghcr.io/pandora-isomemo/osteo-bior:main`

- [ ] @jan-abel-inwt We should add the case that a port is already in use to the instructions.

**Comment by arunge** [comment]
By following the above instructions it is not possible to start two containers at the same time. There are options to do so, but those are a bit technical and one must take care of setting new ports in the correct way for each additional container.

**Comment by isomemo** [comment]
@arunge waiting on the script options as we discussed

**Comment by arunge** [comment]
There is a ticket for the scripts task:
- https://github.com/Pandora-IsoMemo/drat/issues/24
