### ISSUE TITLE
instruction to stop a container for all wikis

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/drat#19]
In case the following error occurs
> docker: Error response from daemon: driver failed ... Bind for 0.0.0.0:3838 failed: port is already allocated.

one must **stop the container that is still running**. This can be done as follows:

1. *Check* which container is running with: `docker ps`
  ![image](https://user-images.githubusercontent.com/16759098/210572033-30e9d416-5d7d-4311-9a43-c829812880dc.png)
3. *Stop* the container using exactly the id from above (here `ab2a252f9269`): `docker stop <YOUR_ID>`
4. *Remove* the container using exactly the id from above: `docker rm <YOUR_ID>`
  ![image](https://user-images.githubusercontent.com/16759098/210574291-c57afb39-10d2-449a-a130-9c97c05561d6.png)
6. *Check* if no container is running anymore: `docker ps`
  The table should be empty now:
  ![image](https://user-images.githubusercontent.com/16759098/210574620-5b243071-57ad-4561-ad74-883731cc4f8f.png)

Now, one can start a new container, e.g. with
`docker run -p 3838:3838 ghcr.io/pandora-isomemo/osteo-bior:main`

@jan-abel-inwt We should add the case that a port is already in use to the instructions.

_Originally posted by @arunge in https://github.com/Pandora-IsoMemo/drat/issues/18#issuecomment-1370988290_

**Comment by arunge** [comment]
@jan-abel-inwt Let us shortly talk before you start! :slightly_smiling_face:

**Comment by jan-abel-inwt** [comment]
- [x] osteo-bior
- [ ]  iso-app
- [ ]  bmsc-app
- [ ]  plotr
- [ ] resources
- [ ] Bpred

**Comment by jan-abel-inwt** [comment]
@arunge please have a look at https://github.com/Pandora-IsoMemo/osteo-bior/wiki/FAQ
if it's to your liking, i will add the faq page to the other repos

**Comment by arunge** [comment]
@jan-abel-inwt Yes, the FAQ is ok. 

Additionally, we should think about 
- where to put a link within the installation instructions to this known issue of "port is already allocated".
- we also need a link to the online version (respectively for each app):
  - a link for each version, main and beta? (needs to be confirmed)
  - a note such as under [isomemosearch.com](https://isomemosearch.com/):
  ![image](https://user-images.githubusercontent.com/16759098/211343479-56e4ec3b-b729-46f9-9b81-6212656e862b.png)
- maybe we should change the order: first the docker installation and than the R installation? What do you think, what should be default?

I will open a new issue for above points.

**Comment by jan-abel-inwt** [comment]
> where to put a link within the installation instructions to this known issue of "port is already allocated"

* There is a note at the beginning of the **Getting started** section that points to the faq section for any problems

> we also need a link to the online version

* Links to web apps are placed on the **Home**  section and in the **footer**
  * only the main version are linked (beta, if there is no main version)

> maybe we should change the order: first the docker installation and than the R installation? What do you think, what should be default?

I changed the order
