### ISSUE TITLE
INSTALLATION FORUM

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/drat#2]
## This is a forum for open source community to report installation issues and bugs. Please report your issues in this format:
- Name of Package
- what setup environment you have
- screen shots or error message log 
> - All commands that led to the installation error: 
> - The full output of `sessionInfo()`
> - The output of `options("repos")`

**Comment by arunge** [comment]
This issue is deprecated. Help can be found here: https://github.com/Pandora-IsoMemo/drat/wiki/How-to-report-bugs
I close here.
