### ISSUE TITLE
Retirement of rgdal

### ISSUE THREAD

**Issue by jan-abel-inwt** [Pandora-IsoMemo/drat#22]
The Package `rgdal` that we use in the *iso-memo-app* will retire by the end of 2023. If necessary we have to plan transition to sf/stars/terra functions.

Further Information can be found here:

https://cran.r-project.org/web/packages/rgdal/index.html

https://r-spatial.org/r/2022/04/12/evolution.html

**Comment by arunge** [comment]
@isomemo We discussed during the last meeting that we will not spend time to update the package in advance. If the package `rgdal` will cause problems in the future, we will find a solution later. I am closing here.
