### ISSUE TITLE
Rename all pages "Getting started" to "Local install instructions"

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/drat#23]
@arunge yes rename to "Local install instructions". This should be done for all apps.

_Originally posted by @isomemo in https://github.com/Pandora-IsoMemo/resources/issues/78#issuecomment-1447938805_

**Comment by arunge** [comment]
@jan-abel-inwt Could you rename in the wikis of all apps the page "Getting started" into "Local install instructions" ?

This must be done for
- [ ] https://github.com/Pandora-IsoMemo/resources/wiki/Getting-started
- [ ] https://github.com/Pandora-IsoMemo/iso-app/wiki/Getting-Started
- [ ] https://github.com/Pandora-IsoMemo/bmsc-app/wiki/Getting-started
- [ ] https://github.com/Pandora-IsoMemo/plotr/wiki/Getting-started
- [ ] https://github.com/Pandora-IsoMemo/osteo-bior/wiki/Getting-Started
- [ ] https://github.com/Pandora-IsoMemo/bpred/wiki/Getting-Started

Thanks!

**Comment by isomemo** [comment]
@arunge thanks!
