### ISSUE TITLE
Create scripts to start several apps simultaneously

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/drat#24]
@arunge waiting on the script options as we discussed

_Originally posted by @isomemo in https://github.com/Pandora-IsoMemo/drat/issues/18#issuecomment-1447973918_

**Comment by arunge** [comment]
### Scripts for docker containers

To start several docker containers and use one terminal for all apps: 
- we must start apps running in the background not in the foreground which is currently the case
- we must update the `run docker` commands and name each app

When running in background, 
- apps will run even if the terminal is closed. We need to stop apps with a specific docker command using the name for the app.
- error messages are not displayed. One must use specific commands to see an error message.

We can prepare scripts that contain basic docker commands 
- to check which apps are running
- for other typical use cases, e.g. 
  - closing all running apps, 
  - opening several apps at the same time
 
We must identify the typical use cases here.

**Comment by isomemo** [comment]
@arunge can one use IF conditions in Docker? If, so why cannot we give a list of apps to the user (e.g., 1 PlotR, 2 BMSC, ...). If the user select 2 a stop command is executed (even if no app is running in the background) and then a command is executed to launch BMSC. In this way, you would not need to run all apps in the background.

**Comment by arunge** [comment]
As discussed, we will update the name of the repository "HelperScripts" to "all-in-one-apps". Blank spaces are not allowed in repository names.
