### ISSUE TITLE
Versions missing for some apps

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/drat#25]
Usually, we have two versions (a _main_ and a _beta_ version) for each app. However, for several apps one version is missing:

- BMSC app:
  - Main: -> https://isomemoapp.com/app/bmsc **missing**
  - Beta: -> https://isomemoapp.com/app/bmsc-beta

- BPred:
  - Main: -> https://isomemoapp.com/app/bpred
  - Beta: -> https://isomemoapp.com/app/bpred-beta **server busy?**

- Iso-Memo app:
  - Main: -> https://isomemoapp.com/app/iso-memo-app
  - Beta: -> https://isomemoapp.com/app/iso-memo-app-beta

- OsteoBioR:
  - Main: -> https://isomemoapp.com/app/osteo-bio-r
  - Beta: -> https://isomemoapp.com/app/osteo-bio-r-beta

- PlotR:
  - Main: -> https://isomemoapp.com/app/plotr **missing**
  - Beta: -> https://isomemoapp.com/app/plotr-beta

- ReSources:
  - Main: -> https://isomemoapp.com/app/resources
  - Beta: -> https://isomemoapp.com/app/resources-beta

I do not know why some versions are not there. For BMSC and PlotR a main version seems to be missing or has a different url:

| BMSC app | PlotR |
|---|---|
|![image](https://user-images.githubusercontent.com/16759098/222460899-f8a04491-fdac-4aac-87e9-72046b5307fe.png)|![image](https://user-images.githubusercontent.com/16759098/222459641-bf8a6ae4-4e7d-43f3-abbb-48b07c8c6d66.png)|

For BPred I have a different error message: 

![image](https://user-images.githubusercontent.com/16759098/222459787-a76220bc-a42b-4090-88d4-56f0aff2c932.png)

@jan-abel-inwt Could you check (if needed together with @wahani) if there are apps deployed for the missing versions? And if so, to which url they are pointing? Could you also check for BPred the beta version?

**Comment by jan-abel-inwt** [comment]
* both main version of [bmsc](https://isomemoapp.com/app/bmsc) and [plotr](https://isomemoapp.com/app/plotr) are  online
* the docker image for `bpred-beta` is missing on the server - im looking into it

**Comment by arunge** [comment]
Now, we also have versions running online for:
- https://isomemoapp.com/app/bmsc (main)
- https://isomemoapp.com/app/bpred-beta (beta)
- https://isomemoapp.com/app/plotr (main)
