### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/drat#29]
New names:

- [x] resources -> ReSources
- [x] bpred -> Bpred
- [x] bmsc-app -> BMSC-S
- [x] plotr -> PlotR
- [x] iso-app -> DSSM
- [x] osteo-bior -> OsteoBioR
- [x] MapR

-----

### What needs to be done to rename the repository name:
- rename **repository on github**:
  - https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository
   ![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/13dc7b96-3b2a-413f-8d08-95919f2948d3)
- rename all occurences in the deployment:
  - application.yml on **shinyproxy** naming all apps that are deployed 
    - for `mpi-iso-app` server https://github.com/INWT/mpi-intern-config/blob/main/mpi-iso-app/etc/shinyproxy/application.yml 
    -  for `mpi-iso-search` server https://github.com/INWT/mpi-intern-config/blob/main/mpi-iso-search/etc/shinyproxy/application.yml
  - ~nginx file?~ -> this should not be affected 
    - https://github.com/INWT/mpi-intern-config/blob/main/mpi-iso-app/etc/nginx/sites-enabled/isomemoapp.conf 
    - https://github.com/INWT/mpi-intern-config/blob/main/mpi-iso-app/etc/nginx/sites-enabled/pandoraapp.conf
  - repository names in **jenkins jobs**:
    - automatic code checks and version updates: check 10 jobs https://isomemodb.com/jenkins/job/Pandora-IsoMemo/
    ![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/17626004-3b07-4157-9002-3ee070a64bbf)
    - deployment of apps, etl jobs, api jobs, maintainance: check 15 jobs https://isomemodb.com/jenkins/job/Pandora-IsoMemo/
    ![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/de4e2a11-c006-4af2-b0ff-dd07a0962f0f)

### Do we need to rename the names of the R packages?
If so, than this will impact:
  - on drat: https://github.com/Pandora-IsoMemo/drat/tree/main/docs/src/contrib
  - NOTE: this will impact the archive where previous versions are stored: https://github.com/Pandora-IsoMemo/drat/tree/main/docs/src/contrib/Archive
    - a renaming will not impact drat, drat does not understand renamings
    - drat will treat a package with a different name just such as a **new package**, the old versions will be kept, new versions will have the name of the new repo /package

@jan-abel-inwt I collected the places were changes should be done, could there be any other places that use a repository name?

**Comment by jan-abel-inwt** [comment]
The Renaming of the R-Package will be done in these issues:

https://github.com/Pandora-IsoMemo/Bpred/issues/47
https://github.com/Pandora-IsoMemo/BMSC-S/issues/35
https://github.com/Pandora-IsoMemo/DSSM/issues/220

**Comment by isomemo** [comment]
@arunge @jan-abel-inwt unclear to me what I should do here! Test the renamed repositories?

**Comment by jan-abel-inwt** [comment]
Sorry @isomemo, I somehow didn’t send my message:

While renaming BMSCApp to BMSC-S, I overlooked that a hyphen is not a permissible character in R package names. Possible alternatives could be:

* BMSCS
* bmscS

Does the final 'S' stand for 'shiny'? If so, the following names might also be appropriate:

* BMSCShiny
* bmscSh iny

Alternatively, we could revert to the original name:

* BMSCApp

Lastly, I'd like to mention that we aim to keep R package names consistent with GitHub repository names in the future. However, we could make an exception here if you prefer.

**Comment by isomemo** [comment]
@jan-abel-inwt we have the shiny package and R package. So perhaps an alternative would be:

1) Revert the Shiny app to BMSC
2) Rename the BMSC R package as BMSCR

what do you think?

**Comment by jan-abel-inwt** [comment]
We can do that but i see 2 disadvantages:

1. The BMSC package was available on CRAN until 2019, but was then removed. Do you plan to republish it? If so, would it be a problem for you if the name changes?
2. The renaming of the BMSC package would be addtional work.

**Comment by isomemo** [comment]
@jan-abel-inwt good point to the possibility of republishing the BMSC R package. In that case, please name the Shiny version as BMSCS

**Comment by jan-abel-inwt** [comment]
Thanks @isomemo, BMSCS is a good choice. I'll make the necessary changes. 
For the republishing of BMSC on CRAN, please contact @arunge. Have a great weekend!
