### ISSUE TITLE
Update CRAN mirror

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/drat#30]
In several apps, we still use the MRAN mirror which is not accessible anymore.

Check the setup of `.Rprofiles` files in all apps and update to the correct CRAN mirror if necessary, e.g.:

```
options(repos = c(
    CRAN = "https://packagemanager.posit.co/cran/2021-01-01",
    INWTLab = "https://inwtlab.github.io/drat/",
    PANDORA = "https://Pandora-IsoMemo.github.io/drat/"
  ))
```

Update the `main` branches of:
- [ ] ReSources
- [ ] Bpred
- [ ] BMSC-S
- [ ] PlotR
- [ ] DSSM
- [ ] OsteoBioR

**Comment by jan-abel-inwt** [comment]
The changes are only necessary in the following repositories:

![image](https://github.com/Pandora-IsoMemo/drat/assets/106665518/aba0b5a0-5fc1-49eb-9c6a-5a2b0f0c8b7e)

- [ ] bmsc-app
- [ ] bpred
- [ ] osteo-bior
- [ ] resources
