### ISSUE TITLE
Ensure compliance of CRAN Standard in all NEWS Files

### ISSUE THREAD

**Issue by jan-abel-inwt** [Pandora-IsoMemo/drat#34]
We have to ensure that our News Files have to be structured like this:

```markdown
# AppName <Versionnumber 2>

## New Features

- first feature
- second feature

## bug fixes

- first bug fix

# AppName <Versionnumber 1>

## New Features

- first feature
...
```

If not it can't be rendered in the changelog in the online Documentation (here is a correct [example](https://pandora-isomemo.github.io/MapR/news/index.html) and the [News File](https://github.com/Pandora-IsoMemo/MapR/blob/main/NEWS.md))

---

I will check all relevant Packages:

API-Wrapper-Packages:

- [x] pandora-data
- [x] isomemo-data

Helper-Packages:

- [x] Data Tools
- [x] shiny-tools
- [x] bmsc
- [x] iso-data

App-Packages:

- [x] bmsc-app
- [x] bpred
  - [x] beta
- [x] iso-app
- [x] mapr
- [x] osteo-bior -> https://github.com/Pandora-IsoMemo/OsteoBioR/pull/54
  - [x] beta
- [x] plotr
- [x] resources
- [x] TraceR

**Comment by jan-abel-inwt** [comment]
fyi: @arunge @f-lukas

**Comment by arunge** [comment]
@jan-abel-inwt Good to know, thanks! I can update the news files of the apps together with new features, or we can shortly discuss when to do this best. Let us talk next week about this.

**Comment by arunge** [comment]
all news.md files should be up-to-date now. Can we close here @jan-abel-inwt ?
