### ISSUE TITLE
Provide names for new apps

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/drat#38]
@isomemo We want to develop several new apps (interfaces for already existing R packages). Could you provide names for the new R packages that we will create? We would like to set up respective repositories for the apps.

Please provide your desired names for following new apps:

1. Self-developed AI package (PEITHO)
2. Modified [oxcAAR](https://cran.r-project.org/web/packages/oxcAAR/index.html) package
3. App for network analysis using modified versions of [SNA](https://cran.r-project.org/web/packages/sna/index.html), [TSNA](https://cran.r-project.org/web/packages/tsna/index.html), [NDTV](https://cran.r-project.org/package=ndtv), network, igraph, tidygraph, ggpraph, visNetwork, and networkD3
4. Modified version of [deBInfer](https://cran.r-project.org/web/packages/deBInfer/index.html) 
5. Modified version of [ABM](https://cran.r-project.org/web/packages/ABM/index.html)

**Comment by isomemo** [comment]
@arunge this should be left for later. It would be best to complete current tasks and also implement name changes for current app repositories

**Comment by arunge** [comment]
@isomemo I have some suggestions for the packages from above, similar to our solution for the package "BMSC" -> "BMSCS".

|  | R package | new repository for the shiny app|
|---|---|---|
|1. |"PEITHO" | "PEITHOS"|
|2. |"oxcAAR" | "oxcAARS"|
|3. |"SNA" | "SNAS"|
|4. |"deBInfer" | "deBInferS"|
|5. |"ABM"  | "ABMS"|

Please, feel free to make your suggestions! Or let me know if we just use the suggested names!

**Comment by arunge** [comment]
@isomemo I created two new repositories with the names that I suggested [above](https://github.com/Pandora-IsoMemo/drat/issues/38#issuecomment-2285657824), 
- [deBInferS](https://github.com/Pandora-IsoMemo/deBInferS) and 
- [ABMS](https://github.com/Pandora-IsoMemo/ABMS).
 
We want to push code for first example apps to github. As long as we do not deploy the apps, renaming the repositories (if necessary) will be no issue. Just let me know your thoughts regarding the 5 planed apps!

**Comment by arunge** [comment]
@isomemo Additionally to the [above](https://github.com/Pandora-IsoMemo/drat/issues/38#issuecomment-2285657824), please also provide R-package/repository names for the new apps
- [ ] _blog-like app_: ??
- [ ] _inquiry app_: maybe "**InquiryR**" ??

**Comment by isomemo** [comment]
@arunge the names that you proposed are you! However, feedback on some of the apps from external collaborators is quite slow. I was thinking of replacing some of the apps for now. To start with, can we replace ABM by this Python app: https://github.com/AtwalLab/BayesPowerlaw

**Comment by isomemo** [comment]
@arunge yes on InquiryR

**Comment by arunge** [comment]
There is a new ticket regarding the python package. The names above were approved. I am closing here.
