### ISSUE TITLE
CausalR Deployment

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/drat#42]
There are two points left regarding the deployment of [CausalR](https://github.com/Pandora-IsoMemo/CausalR) after we finished: https://github.com/Pandora-IsoMemo/CausalR/pull/26

- [x]  online app
  - [x] -> beta version: https://isomemoapp.com/app/causalr-beta
  - [x] -> main version: from the main branch
- [x]  link to online version on https://isomemoapp.com/

@f-lukas Feel free to start with the deployment of the main branch

**Comment by f-lukas** [comment]
I have added the main app to the application.yml but the app is not yet accessable (same as with our new app oxcaars). I will have to check with @jan-abel-inwt next week about which step I am missing.

**Comment by jan-abel-inwt** [comment]
app was added to the frontend
