### ISSUE TITLE
Update app names in wikis after renaming of apps

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/drat#44]
After we renamed some of the apps, the 
instructions for local installation need to be updated, e.g.:

- https://github.com/Pandora-IsoMemo/DSSM/wiki/Local-install-instructions

If one uses the old name, one can only access an older version of the app. To obtain the most recent version for local use **one must use** the new name, e.g.
```
docker pull ghcr.io/pandora-isomemo/dssm:beta
```
and then
```
docker pull ghcr.io/pandora-isomemo/dssm:beta
```

@jan-abel-inwt Could you make a list, which apps had been renamed and update the instructions respectively?

**Comment by arunge** [comment]
@CarloCocozza This issue might be related to your [note](https://github.com/Pandora-IsoMemo/OsteoBioR/issues/59#issuecomment-2326455418):

> P.S. On a side note, I noticed that both OsteoBioR and IsoMemoApp (DSSM) have not been updated in months on their local version via docker.

Please use
```
docker run -p 3838:3838 ghcr.io/pandora-isomemo/osteobior:beta
```
and
```
docker run -p 3838:3838 ghcr.io/pandora-isomemo/osteobior:beta
```
for the most recent local version of OsteoBioR. Sorry about the circumstances!

**Comment by jan-abel-inwt** [comment]
## Renamed Apps

- [x] [DSSM](https://github.com/Pandora-IsoMemo/DSSM/wiki/Local-install-instructions)
- [ ] [BMSCS](https://github.com/Pandora-IsoMemo/BMSCS/wiki/Local-install-instructions)
- [ ] [OsteoBioR](https://github.com/Pandora-IsoMemo/OsteoBioR/wiki/Local-install-instructions)

only changes in capitalization (docker commands are not affected):

- [x] ReSources
- [x] Bpred
- [x]  PlotR

**Comment by jan-abel-inwt** [comment]
I corrected all docker commands of the renamed apps.
