### ISSUE TITLE
install.packages("PlotR") issues

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/drat#7]
# Download **PlotR** package in R
Run these codes in your local R console:

- `options(repos = c(getOption("repos"), PANDORA = "https://Pandora-IsoMemo.github.io/drat/"))`
- `install.packages("PlotR")`

## How to start the app:
- `library(PlotR)`
- `PlotR::startApplication()`

# HOW TO REPORT BUGS:

If you have issues installing the packages, please report your issue here with the package name and what steps you have already done, preferably as descriptive as possible (screenshots, etc.). We will get back to you as soon as we can to solve the issue.

## Can please provide:

> - All commands that led to the installation error: 
> - The full output of `sessionInfo()`
> - The output of `options("repos")`

**Comment by jroachell15** [comment]
when installing PlotR package, error occured:

```
ERROR: dependencies ‘colourpicker’, ‘shinyalert’ are not available for package ‘PlotR’
* removing ‘/home/ljroachell/R/x86_64-pc-linux-gnu-library/4.1/PlotR’

The downloaded source packages are in
	‘/tmp/RtmpPHJcww/downloaded_packages’
Warning message:
In install.packages("PlotR") :
  installation of package ‘PlotR’ had non-zero exit status
```

**Comment by jan-abel-inwt** [comment]
see https://github.com/Pandora-IsoMemo/plotr/issues/18

content can now be found here: https://github.com/Pandora-IsoMemo/plotr/wiki/
