### ISSUE TITLE
install.packages("BMSCApp") issues

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/drat#8]
# DOWNLOAD INSTALLATION ON LOCAL MACHINE
- First download DOCKER (see instructions: https://docs.docker.com/desktop/windows/install/) and see video instructions (https://www.youtube.com/watch?v=_9AWYlt86B8)
- Next, open your windows CMD line and run these following commands:
  > - download and install BMSC app: `docker pull ghcr.io/pandora-isomemo/bmsc-app:main`
  > - start the app run: `docker run -p 3838:3838 ghcr.io/pandora-isomemo/bmsc-app:main`
  > - this outputs `Listening on http://0.0.0.0:3838`, then copy & paste the `http://0.0.0.0:3838` to your browser to access local version. 
  > - quit the app run: `docker run -p 3838:3838 --rm ghcr.io/pandora-isomemo/bmsc-app:main` or just close the browser window

# HOW TO REPORT BUGS:

If you have issues installing the packages, please report your issue here with the package name and what steps you have already done, preferably as descriptive as possible (screenshots, etc.). We will get back to you as soon as we can to solve the issue.

## Can please provide:

> - All commands that led to the installation error: 
> - The full output of `sessionInfo()`
> - The output of `options("repos")`

**Comment by jroachell15** [comment]
When installing BMSCApp, error occurred:

```
ERROR: dependencies ‘ggplot2’, ‘rstan’ are not available for package ‘BMSC’
* removing ‘/home/ljroachell/R/x86_64-pc-linux-gnu-library/4.1/BMSC’
ERROR: dependencies ‘BMSC’, ‘ggplot2’, ‘rstan’ are not available for package ‘BMSCApp’
* removing ‘/home/ljroachell/R/x86_64-pc-linux-gnu-library/4.1/BMSCApp’

The downloaded source packages are in
	‘/tmp/RtmpPHJcww/downloaded_packages’
Warning messages:
1: In install.packages("BMSCApp") :
  installation of package ‘BMSC’ had non-zero exit status
2: In install.packages("BMSCApp") :
  installation of package ‘BMSCApp’ had non-zero exit status
```

**Comment by jan-abel-inwt** [comment]
see https://github.com/Pandora-IsoMemo/bmsc-app/issues/15

content can now be found here: https://github.com/Pandora-IsoMemo/bmsc-app/wiki/
