### ISSUE TITLE
Loading more than two apps at once, but the last app is not correctly started

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/drat#9]
Mar 21. Meeting with Carlo for installation bugs of ReSources and IsoMemoPandora

- First installed ReSourced together no problem and initiated the app
- Install IsoMemo app, but when StartApplication(), the Resource App still appeared to be initiated. 

@wahani is it possible to be able to start more than one app at once locally? For example, the user wants to run both ReSources and Isomemo App? Does the user have to start more than one R sessions in order to do this?

**Comment by wahani** [comment]
> is it possible to be able to start more than one app at once locally? For example, the user wants to run both ReSources and Isomemo App? Does the user have to start more than one R sessions in order to do this?

Yes that is possible. Like you say, you need two start two instances of R and each of them can serve one app. You would have to make sure that they are hosted an different ports. I think this would require a change of the default parameters when the app is started. E.g. in https://github.com/Pandora-IsoMemo/resources/blob/2f4ff97dc396309d96f15a8179ecd080fc7e626f/R/00-startApplication.R#L7 and in every other app I assume we have a function called `startApplication`. They accept an argument port, which needs to be different for the two apps. For example one may run on 4242, the default, the other one on 4243.

Does this resolve your issue locally?

**Comment by arunge** [comment]
@CarloCocozza Did this issue occur when you installed the apps? Did the [explanation above](https://github.com/Pandora-IsoMemo/drat/issues/9#issuecomment-1079067823) help?

If you don't mind I will close the ticket. If there are open questions, feel free to re-open the ticket. Thanks! :slightly_smiling_face:
